//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetNotrePetiteCuisine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetNotrePetiteCuisine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Baneau_orchiettas {
            get {
                object obj = ResourceManager.GetObject("Baneau_orchiettas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap breakfast_690128_1920 {
            get {
                object obj = ResourceManager.GetObject("breakfast_690128_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burger_2559087_1920 {
            get {
                object obj = ResourceManager.GetObject("burger_2559087_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap burger_731298_1920 {
            get {
                object obj = ResourceManager.GetObject("burger_731298_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chef_icon {
            get {
                object obj = ResourceManager.GetObject("chef_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChefIcon3 {
            get {
                object obj = ResourceManager.GetObject("ChefIcon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_up_1854245_1920 {
            get {
                object obj = ResourceManager.GetObject("close_up_1854245_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cooking_2132874_1920 {
            get {
                object obj = ResourceManager.GetObject("cooking_2132874_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CookSymbole {
            get {
                object obj = ResourceManager.GetObject("CookSymbole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###################
        ///-- DROP EVENT IF EXISTS
        ///-- #########################
        ///DROP EVENT IF EXISTS product_stock_manager;
        ///
        ///-- #########################
        ///-- EVENT EVERY MONDAY
        ///-- #########################
        ///CREATE EVENT PRODUCT_STOCK_MANAGER ON SCHEDULE EVERY 1 WEEK STARTS CURRENT_DATE + INTERVAL 6 - WEEKDAY(CURRENT_DATE) DAY
        ///DO BEGIN
        ///  -- To update min_quantity
        ///  UPDATE PRODUCT SET min_quantity = min_quantity + (min_quantity - quantity);
        ///
        ///  -- To update quantity and max_quantity
        ///  UPDATE PRODUCT SET max_quantity =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CREATE_EVENTS {
            get {
                return ResourceManager.GetString("CREATE_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- #########################
        ///-- DROP TABLE IF EXISTS
        ///-- #########################
        ///DROP TABLE IF EXISTS DASHBOARD;
        ///DROP TABLE IF EXISTS HAS_PRODUCT;
        ///DROP TABLE IF EXISTS PRODUCT;
        ///DROP TABLE IF EXISTS SUPPLIER;
        ///DROP TABLE IF EXISTS IS_IN_CART_OF;
        ///DROP TABLE IF EXISTS IS_IN_ORDERTYPE;
        ///DROP TABLE IF EXISTS RECIPE;
        ///DROP TABLE IF EXISTS ORDERTYPE;
        ///DROP TABLE IF EXISTS ADMIN;
        ///DROP TABLE IF EXISTS RECIPE_CREATOR;
        ///DROP TABLE IF EXISTS CLIENT;
        ///
        ///
        ///-- #########################
        ///-- CREATE TABLE
        ///-- ######################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CREATE_TABLES {
            get {
                return ResourceManager.GetString("CREATE_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- #########################
        ///-- DROP TRIGGER IF EXISTS
        ///-- #########################
        ///DROP TRIGGER IF EXISTS AFTER_ORDERTYPE_INSERT;
        ///DROP TRIGGER IF EXISTS BEFORE_RECIPE_UPDATE;
        ///DROP TRIGGER IF EXISTS AFTER_IS_IN_ORDERTYPE_INSERT;
        ///
        ///-- #########################
        ///-- TRIGGER
        ///-- #########################
        ///
        ///-- AFTER IS_IN_ORDERTYPE INSERT
        ///CREATE TRIGGER AFTER_ORDERTYPE_INSERT AFTER INSERT ON ORDERTYPE FOR EACH ROW
        ///BEGIN
        ///  -- To remove the client cart
        ///  DELETE FROM IS_IN_CART_OF WHERE client_id = NEW.client_id;
        ///
        ///  -- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CREATE_TRIGGERS {
            get {
                return ResourceManager.GetString("CREATE_TRIGGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cupcakes_690040_1920 {
            get {
                object obj = ResourceManager.GetObject("cupcakes_690040_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DemiBol {
            get {
                object obj = ResourceManager.GetObject("DemiBol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epinards_1920_1280 {
            get {
                object obj = ResourceManager.GetObject("epinards_1920_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fennel_yogurt_dip_2_Basically {
            get {
                object obj = ResourceManager.GetObject("fennel_yogurt_dip_2_Basically", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Food {
            get {
                object obj = ResourceManager.GetObject("Food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freuits_rouges_1920_1280 {
            get {
                object obj = ResourceManager.GetObject("freuits_rouges_1920_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HLY_FGFP_Kale_Pesto_1x1 {
            get {
                object obj = ResourceManager.GetObject("HLY_FGFP_Kale_Pesto_1x1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoNpC2 {
            get {
                object obj = ResourceManager.GetObject("LogoNpC2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Meat2Dennis {
            get {
                object obj = ResourceManager.GetObject("Meat2Dennis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MeatDennis {
            get {
                object obj = ResourceManager.GetObject("MeatDennis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap noodle_1303003_1920 {
            get {
                object obj = ResourceManager.GetObject("noodle_1303003_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap omelet_933514_1920 {
            get {
                object obj = ResourceManager.GetObject("omelet_933514_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Orecchiette_Pasta_with_Shish_Barak {
            get {
                object obj = ResourceManager.GetObject("Orecchiette_Pasta_with_Shish_Barak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PastaBowl {
            get {
                object obj = ResourceManager.GetObject("PastaBowl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PastaDennis {
            get {
                object obj = ResourceManager.GetObject("PastaDennis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_plats {
            get {
                object obj = ResourceManager.GetObject("photo_plats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_3007395_1920 {
            get {
                object obj = ResourceManager.GetObject("pizza_3007395_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raisins_1920_1280 {
            get {
                object obj = ResourceManager.GetObject("raisins_1920_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salad_1786327_1920 {
            get {
                object obj = ResourceManager.GetObject("salad_1786327_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spaghetti_660748_1920 {
            get {
                object obj = ResourceManager.GetObject("spaghetti_660748_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spinach_791629_1920 {
            get {
                object obj = ResourceManager.GetObject("spinach_791629_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steak_1081819_1920 {
            get {
                object obj = ResourceManager.GetObject("steak_1081819_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steak_978654_1920 {
            get {
                object obj = ResourceManager.GetObject("steak_978654_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
